#!/usr/bin/env bash

echo ".dotfiles/" >> .gitignore

git clone --bare https://github.com/niatran93/dotfiles.git $HOME/.dotfiles

echo "alias dot='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'" >> $HOME/.bashrc

dot checkout
if [ $? = 0 ]; then
  echo "Checked out dotfiles";
  else
    echo "Removing existing dotfiles";
    dot checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} rm {}
fi;

dot checkout
dot config status.showUntrackedFiles no
